image: nvidia/cuda:9.0-devel

before_script:
  - apt-get update && apt-get install -y --no-install-recommends cmake doxygen

stages:
  - prepare
  - pages
  - test

prepare:
  stage: prepare
  script:
  - mkdir build
  - cd build/
  - cmake ..
  artifacts:
    paths:
    - build

pages:
  stage: pages
  script:
  - doxygen build/docs/Doxyfile
  - mv build/docs/doc_doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - cd build/
  - make