image: nvidia/cuda:9.0-devel

before_script:
  - apt-get update && apt-get install -y --no-install-recommends cmake doxygen

stages:
  - prepare
  - build

prepare:
  stage: prepare
  script:
  - mkdir build
  - cd build/
  - cmake -DCUDA_VERBOSE_BUILD=ON ..
  artifacts:
    paths:
    - build

pages:
  image: aergus/latex
  stage: build
  script:
  - doxygen build/docs/Doxyfile
  - mv build/docs/doc_doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

# Not enabled yet, gcc has many errors. I'll fix them once I get access to a Unix machine with a GPU.
.test_compile:
  stage: build
  script:
  - cd build/
  - make