image: nvidia/cuda:9.0-devel

before_script:
  - apt-get update && apt-get install -y --no-install-recommends cmake doxygen

stages:
  - prepare
  - build

prepare:
  stage: prepare
  script:
  - mkdir build
  - cd build/
  - wget -O Eigen.tar.gz https://bitbucket.org/eigen/eigen/get/3.3.2.tar.gz && tar -xzf Eigen.tar.gz
  - cmake -DCMAKE_MODULE_PATH=eigen-eigen-da9b4e14c255/cmake/ ..
  artifacts:
    paths:
    - build

pages:
  stage: build
  script:
  - doxygen build/docs/Doxyfile
  - mv build/docs/doc_doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

test_compile:
  stage: build
  script:
  - cd build/
  - make